# -*- coding: utf-8 -*-
"""Testing Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0tgfK17QYZBTniK1eoV6MbGqcFRsIoW
"""

!pip install -q streamlit pyngrok openpyxl

from google.colab import files

uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# # Carga de datos
# 
# @st.cache_data
# def load_data(path: str):
#     df = pd.read_excel(path)
#     # Columna auxiliar con nombre completo del vendedor
#     df["VENDOR"] = df["NAME"] + " " + df["LASTNAME"]
#     return df
# 
# #Cree el data frame
# df = load_data("sellers.xlsx")
# 
# st.set_page_config(
#     page_title="Sellers Dashboard",
#     layout="wide"
# )
# 
# st.title("📊 Sellers Dashboard")
# 
# st.markdown(
#     """
#     Dashboard para explorar los datos de ventas por **Región**,
#     visualizar **Units Sold**, **Total Sales** y **Sales Average**,
#     y consultar información de un **vendedor específico**.
#     """
# )
# 
# #cree algunos filtros
# st.sidebar.header("Filtros")
# 
# regions = ["All"] + sorted(df["REGION"].unique().tolist())
# region_selected = st.sidebar.selectbox("Selecciona Región", regions)
# 
# #Por region
# if region_selected != "All":
#     df_filtered = df[df["REGION"] == region_selected]
# else:
#     df_filtered = df.copy()
# 
# st.sidebar.markdown("---")
# 
# # Selector de vendedor
# vendors_filtered = sorted(df_filtered["VENDOR"].unique().tolist())
# vendor_selected = st.sidebar.selectbox("Selecciona vendedor", ["(Ninguno)"] + vendors_filtered)
# 
# 
# #Tabla principal
# with st.container():
#     st.subheader("📄 Tabla de datos (filtrada por Región)")
# 
# 
#     default_cols = ["REGION", "ID", "VENDOR", "INCOME", "SOLD UNITS", "TOTAL SALES", "SALES AVERAGE"]
#     cols_to_show = st.multiselect(
#         "Columnas a mostrar:",
#         options=df_filtered.columns.tolist(),
#         default=[c for c in default_cols if c in df_filtered.columns],
#     )
# 
#     st.dataframe(df_filtered[cols_to_show], use_container_width=True)
#     st.caption(f"Filas mostradas: {len(df_filtered)}")
# 
# #Graficas
# st.markdown("---")
# st.subheader("📈 Resumen de ventas por Región")
# 
# tab_units, tab_total, tab_avg = st.tabs(
#     ["Units Sold", "Total Sales", "Sales Average"]
# )
# 
# 
# df_region = (
#     df_filtered
#     .groupby("REGION", as_index=False)
#     .agg({
#         "SOLD UNITS": "sum",
#         "TOTAL SALES": "sum",
#         "SALES AVERAGE": "mean"
#     })
# )
# 
# with tab_units:
#     st.markdown("### Units Sold por Región")
#     st.bar_chart(
#         df_region.set_index("REGION")["SOLD UNITS"],
#         use_container_width=True
#     )
# 
# with tab_total:
#     st.markdown("### Total Sales por Región")
#     st.bar_chart(
#         df_region.set_index("REGION")["TOTAL SALES"],
#         use_container_width=True
#     )
# 
# with tab_avg:
#     st.markdown("### Sales Average por Región")
#     st.bar_chart(
#         df_region.set_index("REGION")["SALES AVERAGE"],
#         use_container_width=True
#     )
# 
# #Filtrar y mostrar datos de vendedor
# st.markdown("---")
# with st.container():
#     st.subheader("🧑‍💼 Detalle de vendedor")
# 
#     if vendor_selected != "(Ninguno)":
#         vendor_data = df[df["VENDOR"] == vendor_selected]
# 
#         col1, col2, col3, col4 = st.columns(4)
#         with col1:
#             st.metric("Región", vendor_data["REGION"].iloc[0])
#         with col2:
#             st.metric("Income", f"{vendor_data['INCOME'].iloc[0]:,}")
#         with col3:
#             st.metric("Units Sold", f"{vendor_data['SOLD UNITS'].iloc[0]:,}")
#         with col4:
#             st.metric("Total Sales", f"{vendor_data['TOTAL SALES'].iloc[0]:,}")
# 
#         st.markdown("#### Fila completa del vendedor")
#         st.table(
#             vendor_data[
#                 ["REGION", "ID", "NAME", "LASTNAME", "INCOME",
#                  "SOLD UNITS", "TOTAL SALES", "SALES AVERAGE"]
#             ]
#         )
#     else:
#         st.info("Selecciona un vendedor en la barra lateral para ver el detalle.")
# 
# #Descarga
# st.markdown("---")
# with st.expander("⬇️ Descargar datos filtrados"):
#     csv = df_filtered.to_csv(index=False).encode("utf-8")
#     st.download_button(
#         "Descargar como CSV",
#         data=csv,
#         file_name="sellers_filtered.csv",
#         mime="text/csv"
#     )
#

from pyngrok import ngrok
#Puse mi codigo de streamlit de mi cuenta
ngrok.set_auth_token("35f7zylxve92KvcFyVbi6m4q7x1_44DNaDf8mBV4UzxqnwiVs")

from pyngrok import ngrok
import time
import os

# Cerrar túneles previos
ngrok.kill()

# Inicia el streamlit y me manda un url
os.system("streamlit run app.py --server.port 8501 --server.address 0.0.0.0 &> /content/streamlit.log &")


public_url = ngrok.connect(8501).public_url
print(public_url)